name: BloodMoon
version: 0.6
main: org.spectralmemories.bloodmoon.Bloodmoon
api-version: 1.14
authors: [SpectralMemories]
description: A bloon moon shines every couple of nights
commands:
  bloodmoon:
    description: Base command. Should be followed by either show, start, stop or reload
  #remove it before building
  testsuite:
    description: Runs tests
    permission-message: "Nope"
    permission: "bloodmoon.reload"
permissions:
  bloodmoon.bloodmoon:
    description: Allows to run the base bloodmoon command
    default: true
  bloodmoon.show:
    description: Allows to see when a new bloodmoon will take place
    default: true
  bloodmoon.start:
    description: Allows to start a bloodmoon
    default: op
  bloodmoon.stop:
    description: Allows to end a bloodmoon
    default: op
  bloodmoon.reload:
    description: Allows to reload config files
    default: op