name: BloodMoon
version: 0.6
main: org.spectralmemories.bloodmoon.Bloodmoon
api-version: 1.14
authors: [SpectralMemories]
description: A bloon moon shines every couple of nights
commands:
  bloodmoon:
    description: Shows the days left before the next BloodMoon
    permission: "bloodmoon.bloodmoon"
    permission-message: "You do not have the permission to do that"
  startbloodmoon:
    description: Starts a BloodMoon now
    permission: "bloodmoon.start"
    permission-message: "You do not have the permission to do that"
  endbloodmoon:
    description: Ends a BloodMoon now
    permission: "bloodmoon.end"
    permission-message: "You do not have the permission to do that"
  reloadbloodmoon:
    description: Reloads both the config and the locale file
    permission: "bloodmoon.reload"
    permission-message: "You do not have the permission to do that"
  #remove it before building
  testsuite:
    description: Runs tests
    permission-message: "Nope"
    permission: "bloodmoon.reload"
permissions:
  bloodmoon.bloodmoon:
    description: Allows to run the bloodmoon command
    default: true
  bloodmoon.start:
    description: Allows to start a bloodmoon
    default: op
  bloodmoon.end:
    description: Allows to end a bloodmoon
    default: op
  bloodmoon.reload:
    description: Allows to reload config files
    default: op